# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'empty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'RealmSwift'
pod 'Firebase'
pod 'Firebase/Database'
pod 'PMAlertController'
	
  target 'emptyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emptyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
